In [5]:
import pandas as pd

def load_and_rename_data(csv_path, code_to_value):
    """
    Load a CSV file and rename its columns using a code-to-value mapping.
    """
    df = pd.read_csv(csv_path)
    df.rename(columns=code_to_name, inplace=True)
    return df

In [6]:
def merge_dataframes(df1, df2, on_columns, suffixes):
    """
    Merge two DataFrames on specified columns.
    """
    merged_df = pd.merge(df1, df2, on=on_columns, how='left', suffixes='_df3')
    return merged_df

In [7]:
def discard_columns_with_missing_values(df, threshold=50):
    """
    Discard columns where more than a specified percentage of values are missing.
    """
    missing_percentage = df.isnull().mean() * 100
    columns_to_drop = missing_percentage[missing_percentage > threshold].index
    df.drop(columns=columns_to_drop, inplace=True)
    return df

In [8]:
def perform_dynamic_correlation(df, source_columns):
    """
    Perform dynamic correlation between columns in the DataFrame.
    """
    for column in source_columns:
        if column + '_df3' in df.columns:  # Check if the corresponding _csv3 column exists
            # Create a mask to identify rows where the data is different
            mask = df[column] != df[f'{column}_df3']
            
            # Apply correlation only to rows where data is different
            df[f'{column}_status'] = df.apply(
                lambda 
                    row: f"{row[column]} ({row[f'{column}_df3']})" 
                if 
                    pd.notna(row[f'{column}_df3']) 
                and 
                    row[column] != row[f'{column}_df3'] 
                else 
                    row[column],
                    axis=1
            )
            
            # Drop the intermediate _csv3 column if no correlation was needed
            if not mask.any():  # If all rows are identical, drop the _csv3 column
                df.drop(columns=[f'{column}_df3'], inplace=True)
    return df

In [13]:
def stroke_risk():
    
    # Load the CSV files
    df1 = pd.read_csv('./synthetic-data/stroke-risk/synthea-stroke-dataset-codes.csv', low_memory=False)
    df2 = pd.read_csv('./synthetic-data/stroke-risk/synthea-pt30k-stroke-ml-table-sel.csv', low_memory=False)
    df3 = pd.read_csv('./synthetic-data/stroke-risk/synthea-pt30k-stroke-ml-table-sel-convert.csv', low_memory=False)
    
    # Create a dictionary mapping codes to values
    code_to_name = dict(zip(df1['code'], df1['name']))

    # Rename columns in df2 and df3 using the mapping dictionary
    df2.rename(columns=code_to_name, inplace=True)
    df3.rename(columns=code_to_name, inplace=True)

    # Merge df2 and df3 on 'ptnum' and 'label'
    merged_df = pd.merge(df2, df3, on=['ptnum', 'label'], how='left', suffixes=('', '_df3'))

    # Create df4 as a copy of the merged DataFrame
    df4 = merged_df.copy()

    # Discard columns with more than 50% missing values
    df4 = discard_columns_with_missing_values(df4, threshold=50)

    # Perform dynamic correlation on df4
    df4 = perform_dynamic_correlation(df4, source_columns=df2.columns)

    # Save df4 to a new CSV file
    df4.to_csv('stroke_data.csv', index=False)

    # Display df4 for verification
    print(df4)

In [14]:
stroke_risk()

        ptnum  label  scc      race marital       ethnic gender  \
0       p3686      1  162     white       m  nonhispanic      m
1       p4204      1  155     asian       m  nonhispanic      m
2      p14352      1  147     white       m  nonhispanic      f
3      p28589      1  147     white       m  nonhispanic      m
4      p28075      1  145     asian       m  nonhispanic      m
...       ...    ...  ...       ...     ...          ...    ...
16050   p9840      0   70     asian       m  nonhispanic      f
16051   p9866      0   70     white       m  nonhispanic      f
16052   p9892      0   70     white       m  nonhispanic      f
16053   p9912      0   70     white       m  nonhispanic      m
16054   p9965      0   70  hawaiian       m  nonhispanic      m

               state   age Full-time employment (finding)  ...  \
0      massachusetts  95.0                           True  ...
1      massachusetts  71.0                           True  ...
2      massachusetts  97.0                           True  ...
3      massachusetts  83.0                           True  ...
4      massachusetts  77.0                           True  ...
...              ...   ...                            ...  ...
16050  massachusetts  64.0                            NaN  ...
16051  massachusetts  48.0                           True  ...
16052  massachusetts  39.0                            NaN  ...
16053  massachusetts  57.0                           True  ...
16054  massachusetts  67.0                           True  ...

      Social isolation (finding)_status  \
0                                  True
1                                  True
2                                  True
3                                  True
4                                  True
...                                 ...
16050                               NaN
16051                               NaN
16052                               NaN
16053                              True
16054                              True

       Limited social contact (finding)_status   Chloride_status  \
0                                         True  110.7 (abnormal)
1                                         True  109.6 (abnormal)
2                                         True    103.9 (normal)
3                                         True  107.7 (abnormal)
4                                         True    102.9 (normal)
...                                        ...               ...
16050                                     True   106.11 (normal)
16051                                      NaN               NaN
16052                                      NaN   102.85 (normal)
16053                                     True   106.11 (normal)
16054                                     True               NaN

       Glucose_status    Sodium_status Potassium_status  \
0       86.6 (normal)   136.7 (normal)     3.7 (normal)
1      112.1 (normal)   140.5 (normal)     4.8 (normal)
2       89.7 (normal)   137.7 (normal)     4.4 (normal)
3       83.7 (normal)   138.4 (normal)     4.7 (normal)
4      118.2 (normal)   140.2 (normal)     4.6 (normal)
...               ...              ...              ...
16050  79.06 (normal)  140.03 (normal)    4.54 (normal)
16051             NaN              NaN              NaN
16052  81.55 (normal)  138.35 (normal)     4.7 (normal)
16053  84.41 (normal)  140.22 (normal)    4.22 (normal)
16054             NaN              NaN              NaN

       Td (adult) preservative free_status  \
0                                     True
1                                      NaN
2                                     True
3                                     True
4                                     True
...                                    ...
16050                                 True
16051                                 True
16052                                 True
16053                                 True
16054                                 True

       Hemoglobin A1c/Hemoglobin.total in Blood_status  \
0                                       3.1 (abnormal)
1                                       7.0 (abnormal)
2                                         5.5 (normal)
3                                         5.5 (normal)
4                                       3.9 (abnormal)
...                                                ...
16050                                  6.06 (abnormal)
16051                                              NaN
16052                                  6.05 (abnormal)
16053                                  6.08 (abnormal)
16054                                              NaN

       Not in labor force (finding)_status  Viral sinusitis (disorder)_status
0                                     True                               True
1                                      NaN                               True
2                                     True                                NaN
3                                     True                                NaN
4                                     True                               True
...                                    ...                                ...
16050                                  NaN                                NaN
16051                                  NaN                               True
16052                                  NaN                               True
16053                                 True                                NaN
16054                                 True                               True

[16055 rows x 153 columns]

In [17]:
def lung_cancer_risk():
    
    # Load the CSV files
    df1 = pd.read_csv('./synthetic-data/lung-cancer-risk/synthea-lc-dataset-codes.csv', low_memory=False)
    df2 = pd.read_csv('./synthetic-data/lung-cancer-risk/synthea-pt30k4-lc-data-sel.csv', low_memory=False)
    df3 = pd.read_csv('./synthetic-data/lung-cancer-risk/synthea-pt30k4-lc-data-sel-convert.csv', low_memory=False)
    
    # Create a dictionary mapping codes to values
    code_to_name = dict(zip(df1['code'], df1['name']))

    # Rename columns in df2 and df3 using the mapping dictionary
    df2.rename(columns=code_to_name, inplace=True)
    df3.rename(columns=code_to_name, inplace=True)

    # Merge df2 and df3 on 'ptnum' and 'label'
    merged_df = pd.merge(df2, df3, on=['ptnum', 'label'], how='left', suffixes=('', '_df3'))

    # Create df4 as a copy of the merged DataFrame
    df4 = merged_df.copy()

    # Discard columns with more than 50% missing values
    df4 = discard_columns_with_missing_values(df4, threshold=50)

    # Perform dynamic correlation on df4
    df4 = perform_dynamic_correlation(df4, source_columns=df2.columns)

    # Save df4 to a new CSV file
    df4.to_csv('lung_cancer_data.csv', index=False)

    # Display df4 for verification
    print(df4)

In [18]:
lung_cancer_risk()

       ptnum  label  scc   race marital       ethnic gender          state  \
0      p3818      1  165  white       m  nonhispanic      m  massachusetts
1     p23282      1  146  white       m  nonhispanic      m  massachusetts
2     p23869      1  144  white       m  nonhispanic      m  massachusetts
3      p9666      1  135  white       m  nonhispanic      m  massachusetts
4     p24930      1  133  white       m  nonhispanic      m  massachusetts
...      ...    ...  ...    ...     ...          ...    ...            ...
4379   p9627      0  100  white       s  nonhispanic      m  massachusetts
4380   p9759      0  100  white       m  nonhispanic      f  massachusetts
4381   p9800      0  100  white       m  nonhispanic      f  massachusetts
4382   p9901      0  100  white       m     hispanic      f  massachusetts
4383   p9912      0  100  white       m  nonhispanic      f  massachusetts

       age Influenza  seasonal  injectable  preservative free  ...  \
0     68.0                                               True  ...
1     69.0                                               True  ...
2     79.0                                               True  ...
3     67.0                                               True  ...
4     72.0                                               True  ...
...    ...                                                ...  ...
4379  70.0                                               True  ...
4380  48.0                                               True  ...
4381  44.0                                               True  ...
4382  39.0                                               True  ...
4383  69.0                                               True  ...

      Td (adult) preservative free_status  \
0                                     NaN
1                                     NaN
2                                     NaN
3                                     NaN
4                                    True
...                                   ...
4379                                 True
4380                                 True
4381                                 True
4382                                 True
4383                                 True

      Victim of intimate partner abuse (finding)_status  \
0                                                  True
1                                                   NaN
2                                                   NaN
3                                                  True
4                                                  True
...                                                 ...
4379                                               True
4380                                                NaN
4381                                                NaN
4382                                               True
4383                                               True

      Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma_status  \
0                                      159.7 (abnormal)
1                                         31.6 (normal)
2                                         29.0 (normal)
3                                       40.8 (abnormal)
4                                       27.2 (abnormal)
...                                                 ...
4379                                     30.03 (normal)
4380                                                NaN
4381                                    59.9 (abnormal)
4382                                                NaN
4383                                    37.3 (abnormal)

      Albumin_status  \
0       5.1 (normal)
1       4.9 (normal)
2       5.0 (normal)
3       4.3 (normal)
4       4.7 (normal)
...              ...
4379   4.48 (normal)
4380             NaN
4381    5.1 (normal)
4382             NaN
4383   4.39 (normal)

      Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma_status  \
0                                      172.7 (abnormal)
1                                         27.8 (normal)
2                                        6.9 (abnormal)
3                                       38.5 (abnormal)
4                                       35.6 (abnormal)
...                                                 ...
4379                                     22.05 (normal)
4380                                                NaN
4381                                      11.3 (normal)
4382                                                NaN
4383                                     19.74 (normal)

      Bilirubin.total [Mass/volume] in Serum or Plasma_status  \
0                                          1.1 (normal)
1                                          0.3 (normal)
2                                          0.5 (normal)
3                                          0.1 (normal)
4                                          0.7 (normal)
...                                                 ...
4379                                      0.77 (normal)
4380                                                NaN
4381                                       0.6 (normal)
4382                                                NaN
4383                                      0.67 (normal)

     Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma_status  \
0                                       48.1 (abnormal)
1                                       24.7 (abnormal)
2                                       45.9 (abnormal)
3                                       41.4 (abnormal)
4                                       47.7 (abnormal)
...                                                 ...
4379                                   66.25 (abnormal)
4380                                                NaN
4381                                    51.9 (abnormal)
4382                                                NaN
4383                                    66.8 (abnormal)

     Initial patient assessment (procedure)_status  \
0                                             True
1                                             True
2                                             True
3                                             True
4                                             True
...                                            ...
4379                                          True
4380                                           NaN
4381                                           NaN
4382                                           NaN
4383                                          True

      Development of individualized plan of care (procedure)_status  \
0                                                  True
1                                                  True
2                                                  True
3                                                  True
4                                                  True
...                                                 ...
4379                                               True
4380                                                NaN
4381                                                NaN
4382                                                NaN
4383                                               True

      Body temperature_status
0               37.2 (normal)
1                         NaN
2               37.1 (normal)
3                         NaN
4             38.0 (abnormal)
...                       ...
4379                      NaN
4380          37.6 (abnormal)
4381            37.2 (normal)
4382            37.0 (normal)
4383            37.1 (normal)

[4384 rows x 186 columns]